version: '3.5'

services:
  teknologr:
    image: teknologr:latest
    hostname: teknologr
    env_file:
      - teknologr.env
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    hostname: nginx
    env_file:
      - teknologr.env
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../teknologr/members/static:/var/www/teknologr_static/static
    depends_on:
      - teknologr
  
  postgres:
    image: postgres:12.0-alpine
    hostname: postgres
    volumes:
      - teknologr_data:/var/lib/postgresql/data/
    env_file:
      - teknologr.env

  openldap:
    image: osixia/openldap:latest
    hostname: openldap
    command: "--copy-service --loglevel debug"
    volumes:
      - ./permissions.ldif:/container/service/slapd/assets/config/bootstrap/ldif/02-security.ldif
      - ./init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif
    env_file:
      - teknologr.env

volumes:
  teknologr_data:
