language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# command to run tests
script: cd teknologr && coverage run --source members,api manage.py test

after_success:
  coveralls --rcfile=../.coveragerc

#Turn off mail notification
notifications:
  email: false
