name: Django CI

on:
  push:
    branches: [ "feature/github-action" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install OpenLDAP dependencies
      run: sudo apt install libsasl2-dev python3-dev libldap2-dev libssl-dev
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install latest pip
      run: python -m pip install --upgrade pip
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: python manage.py test
